Add basic linter checks

diff --git a/.github/workflows/ci-cd-workflow.yml b/.github/workflows/ci-cd-workflow.yml
--- a/.github/workflows/ci-cd-workflow.yml
+++ b/.github/workflows/ci-cd-workflow.yml
@@ -20,30 +20,29 @@ jobs:
       run: |
         pip install --upgrade pip
         pip install -e .[dev]
-    # - name: Formatting and linters
-    #   # add (when addressing https://github.com/znicholls/silicone/issues/58)
-    #   # - `pydocstyle src`
-    #   # - `bandit -c .bandit.yml -r src`
-    #   # - `flake8 src tests setup.py` and `pylint src`
-    #   # - black --check src tests setup.py --exclude silicone/_version.py
-    #   # - isort --check-only --quiet --recursive src tests setup.py
-    #   run: |
-    #     black-nb --check notebooks
-    # # # for future
-    # # - name: Build docs
-    # #   # treat warnings as errors (-W)...
-    # #   # ...but not when being nitpicky (-n)
-    # #   run: |
-    # #       sphinx-build -M html docs/source docs/build -qW
-    # #       sphinx-build -M html docs/source docs/build -Eqn -b coverage
-    # #       if [[ -s docs/build/html/python.txt ]]
-    # #       then
-    # #           echo
-    # #           echo \"Error: Documentation missing:\"
-    # #           echo
-    # #           cat docs/build/html/python.txt
-    # #           exit 1
-    # #       fi
+    - name: Formatting and linters
+      # add (when addressing https://github.com/znicholls/silicone/issues/58)
+      # - `pydocstyle src`
+      # - `bandit -c .bandit.yml -r src`
+      # - `flake8 src tests setup.py` and `pylint src`
+      run: |
+        black-nb --check notebooks
+        black --check src tests setup.py --exclude silicone/_version.py
+        isort --check-only --quiet --recursive src tests setup.py
+    - name: Build docs
+      # treat warnings as errors (-W)...
+      # ...but not when being nitpicky (-n)
+      run: |
+          sphinx-build -M html docs/source docs/build -qW
+          sphinx-build -M html docs/source docs/build -Eqn -b coverage
+          if [[ -s docs/build/html/python.txt ]]
+          then
+              echo
+              echo \"Error: Documentation missing:\"
+              echo
+              cat docs/build/html/python.txt
+              exit 1
+          fi
 
   build:
     needs: linting-and-docs
